[workspace]
resolver = "3"
members = ["mcproto", "mcproto-codec", "mcproto-types"]

[workspace.package]
version = "0.2.0"
edition = "2024"
authors = ["MCSLTeam <services@mcsl.com.cn>"]
license = "GPL-3.0-only"
repository = "https://github.com/MCSLTeam/mcproto"

[workspace.dependencies]
fastnbt = "2.6.2"
mcproto-codec = { version = "0.2.0", path = "mcproto-codec" }
mcproto-types = { version = "0.2.0", path = "mcproto-types" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.151"
url = "2.5.7"
