[workspace]
resolver = "3"
members = ["mcproto", "mcproto-codec", "mcproto-types"]

[workspace.package]
version = "0.2.1"
edition = "2024"
authors = ["MCSLTeam <services@mcsl.com.cn>"]
license = "MIT"
repository = "https://github.com/MCSLTeam/mcproto"

[workspace.dependencies]
fastnbt = "2.6.2"
mcproto-codec = { version = "0.2.1", path = "mcproto-codec" }
mcproto-types = { version = "0.2.1", path = "mcproto-types" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.151", features = ["unbounded_depth"] }
serde_stacker = "0.1.14"
url = "2.5.7"
