[workspace]
resolver = "3"
members = ["mcproto", "mcproto-codec", "mcproto-types"]

[workspace.package]
version = "0.2.0"
edition = "2024"
authors = ["MCSLTeam <services@mcsl.com.cn>"]
license = "GPL-3.0-only"
repository = "https://github.com/MCSLTeam/mcproto"

[workspace.dependencies]
fastnbt = "2.6.2"
mcproto-codec = { path = "mcproto-codec" }
