[package]
name = "mcproto"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Minecraft protocol implementation in Rust."
readme = "README.md"
keywords = ["Minecraft", "Serde", "MC", "Protocol", "Quick"]
categories = ["network-programming", "asynchronous", "game-development", "encoding"]

[features]
default = ["codec", "types"]
codec = ["dep:mcproto-codec"]
types = ["codec", "dep:mcproto-types"]
oauth = ["dep:mcproto-oauth"]
[dependencies]
mcproto-codec = { workspace = true, optional = true }
mcproto-types = { workspace = true, optional = true }
mcproto-oauth = { workspace = true, optional = true }
