[package]
name = "mcproto-types"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Minecraft protocol types."
readme = "README.md"
keywords = ["Minecraft", "protocol", "types"]
categories = ["network-programming", "game-development"]

[dependencies]
mcproto-codec.workspace = true
